using System;
using System.Collections.Generic;
using System.Linq;

namespace FuelRushMaui.Services
{
    public class TelemetryFrame
    {
        public float SpeedKmH { get; set; }
        public float SteeringInput { get; set; }
        public bool IsBraking { get; set; }
        public float MinObstacleDistance { get; set; }
        public DateTime Timestamp { get; set; } = DateTime.Now;
    }

    public enum SkillTier
    {
        Rookie,
        Casual,
        Aggressive,
        ProSimulator
    }

    public class AICoPilotPrediction
    {
        /// <summary>
        /// Crash probability value ranging from 0.0 (0%) to 1.0 (100%).
        /// </summary>
        public float CrashProbability { get; set; }

        /// <summary>
        /// Estimated player skill tier based on control smoothness and reaction timing.
        /// </summary>
        public SkillTier EstimatedSkillTier { get; set; }

        /// <summary>
        /// Dynamic Difficulty Adjustment multiplier for traffic/obstacle spawn rates (0.75x to 1.35x).
        /// </summary>
        public float DynamicDifficultyMultiplier { get; set; } = 1.0f;

        /// <summary>
        /// Index of steering smoothness (0.0 = jittery/erratic, 1.0 = buttery smooth).
        /// </summary>
        public float SteeringSmoothnessIndex { get; set; } = 1.0f;

        /// <summary>
        /// Real-time HUD advice or warning generated by the AI Co-Pilot.
        /// </summary>
        public string AdvisoryMessage { get; set; } = "AI CO-PILOT: ONLINE";
    }

    /// <summary>
    /// Advanced Telemetry AI Engine providing real-time risk evaluation and Dynamic Difficulty Adjustment (DDA).
    /// </summary>
    public class AICoPilotService
    {
        private readonly Queue<TelemetryFrame> _telemetryHistory = new();
        private const int MaxHistoryWindow = 60; // 60 frames (~1 second window)
        private int _panicBrakeCount = 0;
        private float _timeSinceLastPanicBrake = 0f;

        public AICoPilotPrediction LastPrediction { get; private set; } = new();

        /// <summary>
        /// Evaluates current frame telemetry and updates AI ML predictions.
        /// </summary>
        public AICoPilotPrediction ProcessTelemetry(
            float speedKmH,
            float steeringInput,
            bool isBraking,
            float minObstacleDistance,
            float deltaTime)
        {
            _timeSinceLastPanicBrake += deltaTime;

            // 1. Record Telemetry Frame
            var frame = new TelemetryFrame
            {
                SpeedKmH = speedKmH,
                SteeringInput = steeringInput,
                IsBraking = isBraking,
                MinObstacleDistance = minObstacleDistance
            };

            _telemetryHistory.Enqueue(frame);
            if (_telemetryHistory.Count > MaxHistoryWindow)
            {
                _telemetryHistory.Dequeue();
            }

            // Track panic braking (high speed + hard braking)
            if (isBraking && speedKmH > 70f && _timeSinceLastPanicBrake > 1.5f)
            {
                _panicBrakeCount++;
                _timeSinceLastPanicBrake = 0f;
            }

            // 2. Compute Steering Smoothness Index (Variance of Steering Derivatives)
            float smoothness = CalculateSteeringSmoothness();

            // 3. Predict Real-Time Crash Probability (Logistic Sigmoid Model)
            float crashRisk = CalculateCrashProbability(speedKmH, steeringInput, minObstacleDistance, smoothness);

            // 4. Determine Player Skill Tier
            SkillTier skill = DetermineSkillTier(speedKmH, smoothness, crashRisk);

            // 5. Compute Dynamic Difficulty Adjustment (DDA) Multiplier
            float ddaMultiplier = CalculateDDAMultiplier(skill, crashRisk);

            // 6. Formulate Advisory Alert
            string advice = GenerateAdvisory(crashRisk, skill, minObstacleDistance);

            LastPrediction = new AICoPilotPrediction
            {
                CrashProbability = crashRisk,
                EstimatedSkillTier = skill,
                DynamicDifficultyMultiplier = ddaMultiplier,
                SteeringSmoothnessIndex = smoothness,
                AdvisoryMessage = advice
            };

            return LastPrediction;
        }

        private float CalculateSteeringSmoothness()
        {
            if (_telemetryHistory.Count < 5) return 1.0f;

            var list = _telemetryHistory.ToList();
            float totalDelta = 0f;

            for (int i = 1; i < list.Count; i++)
            {
                totalDelta += Math.Abs(list[i].SteeringInput - list[i - 1].SteeringInput);
            }

            float avgDelta = totalDelta / (list.Count - 1);
            // Higher delta indicates jerky/erratic steering; scale to 0.0 (erratic) -> 1.0 (smooth)
            return Math.Clamp(1.0f - (avgDelta * 4.0f), 0.1f, 1.0f);
        }

        private float CalculateCrashProbability(float speed, float steerInput, float minObsDist, float smoothness)
        {
            if (minObsDist <= 0f || minObsDist > 600f)
            {
                return 0.05f; // Safe default
            }

            // Time to collision estimate (TTC)
            float speedMs = speed / 3.6f;
            float ttc = speedMs > 0.1f ? (minObsDist / speedMs) : 10f;

            // Logistic Regression Weightings
            float z = 2.5f 
                    - (ttc * 0.85f) 
                    + (Math.Abs(steerInput) * 0.4f) 
                    + ((1.0f - smoothness) * 0.6f);

            // Sigmoid Activation: 1 / (1 + e^-z)
            float probability = (float)(1.0 / (1.0 + Math.Exp(-z)));
            return Math.Clamp(probability, 0.0f, 0.99f);
        }

        private SkillTier DetermineSkillTier(float speed, float smoothness, float crashRisk)
        {
            if (speed > 120f && smoothness > 0.75f && crashRisk < 0.35f)
            {
                return SkillTier.ProSimulator;
            }
            if (speed > 90f && crashRisk < 0.5f)
            {
                return SkillTier.Aggressive;
            }
            if (smoothness > 0.5f)
            {
                return SkillTier.Casual;
            }
            return SkillTier.Rookie;
        }

        private float CalculateDDAMultiplier(SkillTier skill, float crashRisk)
        {
            // If player is struggling (high crash risk), ease obstacle frequency (DDA scaling)
            if (crashRisk > 0.7f)
            {
                return 0.75f;
            }

            return skill switch
            {
                SkillTier.ProSimulator => 1.35f,
                SkillTier.Aggressive => 1.15f,
                SkillTier.Casual => 1.00f,
                _ => 0.85f
            };
        }

        private string GenerateAdvisory(float crashRisk, SkillTier skill, float minObsDist)
        {
            if (crashRisk > 0.75f)
            {
                return "⚠️ AI ALERT: COLLISION IMMINENT - BRAKE NOW!";
            }
            if (minObsDist < 120f && minObsDist > 0f)
            {
                return "⚡ AI CO-PILOT: OBSTACLE CLOSE - EVADE!";
            }
            if (skill == SkillTier.ProSimulator)
            {
                return "🏆 AI CO-PILOT: PRO APEX LINE DETECTED";
            }
            return "🤖 AI CO-PILOT: MONITORING TELEMETRY";
        }
    }
}
